[feature][TDET-50] A DAG for fetching industry codes
DE-ta-e-il/catch-me-my-capital pull request #4
Opened 2024-12-26 09:20 UTC by boolYikes

## 개요
KOSPI, KOSDAQ, GICS의 주식 업종 분류 코드를 가져오는 DAG를 작성
업데이트가 잦지 않으므로 1달에 한 번 풀 리프레시 수행

## 변경 사항
[feat: TDET-50 Attached crawler image to airflow service, tested](https://github.com/DE-ta-e-il/catch-me-my-capital/commit/4fe4d32f3a80f26f67f06b4307083695de6bda7d)
- 셀레니움을 별도 컨테이너에서 사용하려고 이미지를 따로 만들어 씀

[chore: TDET-50 Added logs to gitignore and made changes to docker com…](https://github.com/DE-ta-e-il/catch-me-my-capital/commit/6a20babd1b23eedd7538b322b12a8f236c740638)
- 셀레니움을 DAG 내에서 작성하기로 결정해서 해당 DAG(brz_crawl_image_test.py)는 추진하지 않음

[feat: TDET-50 Added industry code crawling DAG (unfinished), added he…](https://github.com/DE-ta-e-il/catch-me-my-capital/commit/e187dc8c3aa8815273d14602a80f5dad8e2ec4f4)
- 업종 분류 코드 크롤링 대그 초안 작성

[feat: TDET-50 Excluded KRX codes, GICS-only-regime](https://github.com/DE-ta-e-il/catch-me-my-capital/commit/52b22dbaccdbd21a4de41fa1a8dedb1a281e6b6a)
- KRX를 크롤링하여 수집하려고 했다가 막혀서 KOSPI와 KOSDAQ을 제외했었음

[fix: TDET-50 Reworked industry code DAG for new s3 conn method, fixed…](https://github.com/DE-ta-e-il/catch-me-my-capital/commit/d43466092e75634908d8fa1f298d5c1bf0fedfb4)
- 시크릿(커넥션 등)관리를 웹 UI가 아닌 환경변수에서 하도록 변경. KOSPI와 KOSDAQ 부분을 API 조회 방법으로 작성

## 테스트 결과
- 그래프상 정상 작동 확인
![image](https://github.com/user-attachments/assets/b5626936-1d3a-4a1f-a128-8a1edd5bcb72)

- 현재 결정되어있는 파티션 구조로 S3 정상 업로드 확인
![image](https://github.com/user-attachments/assets/834cf45a-39db-449e-83d6-de3b985eb0c1)

- GICS 업종코드
![image](https://github.com/user-attachments/assets/e7601476-2e03-4bc7-8a23-50e57f4ff9bb)

- KOSDAQ 업종코드
![image](https://github.com/user-attachments/assets/a807056b-1518-4d18-8d17-222dff246288)

- KOSPI 업종코드
![image](https://github.com/user-attachments/assets/f4a8642a-4737-4eca-8f70-44f381ea1b8c)

## 리뷰 요청 사항
- context['ti'].xcom_push를 하는 방법과 return으로 값을 넘기는 방법중 우월한 것이 있을까요? (task decorator를 사용하지 않는)
- 옵젝트(딕셔너리, 리스트)를 넘기면서 스트링으로 바뀌고 다시 변환되는 과정이 비효율적이지는 않을까요?

2024-12-26 09:53 UTC, cardia requested changes
1. https://dydwnsekd.tistory.com/107 를 참고해 주세요.
xcom을 따로 설정하지 않는다면, Airflow의 메타 DB에 저장되게 됩니다. 때문에 xcom의 사용은 지양합시다.

2. 가급적이면 리스트, 딕셔너리를 그대로 넘겨서 사용할 수 있으면 제일 좋겠지만, 그렇지 않으면 어쩔 수 없이 마샬링을 해야 하는데요. 그냥 편하게 json을 사용하시면 되겠습니다. 문자열만 받는다면 선택지가 딱히 없기 때문에 비효율적이어도 어쩔 수 없어요.

2024-12-26 09:53 UTC, cardia commented on dags/brz_industry_code_month.py
> +    task01 = PythonOperator(
P1; 변수 이름으로 뭐가 저장되는지 알아야 합니다.

2024-12-26 09:53 UTC, cardia commented on dags/brz_industry_code_month.py
> +                data="{{ task_instance.xcom_pull(task_ids='"
P0; xcom은 어떤 데이터가 얼만큼 들어올지도 모르는 값을 저장해서는 안됩니다.
차라리 하나의 task에서 S3 upload까지 하도록 각 task가 stateless하게 작성되어야합니다.

2024-12-26 10:07 UTC, boolYikes commented on dags/brz_industry_code_month.py
> +                data="{{ task_instance.xcom_pull(task_ids='"
🤔 완료되지 않은 태스크가 있을수도 있기때문일까요? 🤔🤔 python operator 안에 s3 operator를 넣어서 1:1로 만들어보겠습니다!

2024-12-27 04:20 UTC, cardia commented on dags/brz_industry_code_month.py
> +                data="{{ task_instance.xcom_pull(task_ids='"
아니요. xcom이 무거워지게 되면 Airflow 전체에 영향이 가기 때문입니다.

2024-12-27 04:35 UTC, cardia requested changes
비슷한 함수가 세개 동작하는 모습인데요. 인자값만 다르게 주고 동일한 함수를 실행하도록 하는게 좋겠습니다.

2024-12-27 04:35 UTC, cardia commented on dags/brz_crawl_image_test.py
> +import logging
P4; test DAG은 test_를 prefix로 사용하시는게 나중에 Airflow UI 상에서 구분하기 좋습니다.

2024-12-27 04:35 UTC, cardia commented on dags/brz_industry_code_month.py
> +        s3_key=f"bronze/industry_code/date={ds_year}-{ds_month}-{ds_day}/gics_codes_{ds_year}-{ds_month}.json",
P4; 제 취향 & 지금껏 겪어본 곳들에서는 dash를 잘 안쓰긴 합니다. 하지만 취향이니 편한대로 하셔도 될 듯 해요~
다만 프로젝트 전체적으로 컨벤션을 맞춰주세요.

2024-12-27 04:35 UTC, cardia commented on dags/brz_industry_code_month.py
> +S3_BUCKET = os.getenv("S3_BUCKET")
버킷 이름을 환경변수로 넣어주나요??

2024-12-27 04:35 UTC, cardia commented on dags/brz_industry_code_month.py
> +    ctxt["ti"].xcom_push(key="kospi", value=new_items)
P2; S3로 넣어주니까 이 부분은 빼도 되겠죠?

2024-12-27 04:35 UTC, cardia commented on dags/brz_industry_code_month.py
> +    return "puff"
P1; puff에 어떤 의미가 있나요?? 의미 있는 값이 아니면 빼면 좋겠습니다.

2024-12-27 04:35 UTC, cardia commented on dags/brz_industry_code_month.py
> +    upload_kospi = S3CreateObjectOperator(
이....거 동작 하나요?? (동공지진)

2024-12-27 04:35 UTC, cardia commented on dags/brz_industry_code_month.py
> +    ds_year, ds_month, ds_day = "{{ ds }}"[:4], "{{ ds }}"[5:7], "{{ ds }}"[8:10]
P0; 이렇게 파싱하면 안됩니다! datetime으로 올바로 인식시키고 그걸 .year() .month() .day() 등을 써서 파싱하는 방식이 순리입니다.

2024-12-27 04:35 UTC, cardia commented on dags/brz_industry_code_month.py
> +    ds_year, ds_month, ds_day = "{{ ds }}"[:4], "{{ ds }}"[5:7], "{{ ds }}"[8:10]
위에서 받은 date 변수를 쓸 수도 있지 않나요?? 👀

2024-12-27 05:06 UTC, boolYikes commented on dags/brz_industry_code_month.py
> +S3_BUCKET = os.getenv("S3_BUCKET")
넵 .env에 넣는걸로 정했습니다😀

2024-12-27 05:09 UTC, cardia commented on dags/brz_industry_code_month.py
> +S3_BUCKET = os.getenv("S3_BUCKET")
.env는 어디에 있나요??

2024-12-27 05:14 UTC, boolYikes commented on dags/brz_industry_code_month.py
> +S3_BUCKET = os.getenv("S3_BUCKET")
gitignore 리스트라 없지만, 원래는 airflow 프로젝트 루트에 있습니다. docker-compose-dev.yaml에서 
![image](https://github.com/user-attachments/assets/3752c5e4-96f2-4860-b5c5-66052e25652e)
이렇게 추가됐습니다

2024-12-27 05:17 UTC, cardia commented on dags/brz_industry_code_month.py
> +S3_BUCKET = os.getenv("S3_BUCKET")
그럼 안되겠지요 😂  gitignore를 풀어서 함께 올려주세요.
그리고 그러면 Variable 패키지를 사용하셔야 하지 않을까요??

2024-12-27 05:24 UTC, boolYikes commented on dags/brz_industry_code_month.py
> +S3_BUCKET = os.getenv("S3_BUCKET")
🤔음 .env에 AWS키가 들어있는데 괜찮을까요? 아 그리고 Ruff 린터에서 시크릿 푸시를 원천 봉쇄하구있습니다 ㅋㅋ
![image](https://github.com/user-attachments/assets/8db84c00-ca24-4ddb-add1-500706781bb5)

2024-12-27 05:26 UTC, cardia commented on dags/brz_industry_code_month.py
> +S3_BUCKET = os.getenv("S3_BUCKET")
엇 그러면 connection으로 따로 관리를 해주셔야겠죠.
요건 잘 쓰고 계시면 뭐 괜찮습니다.
DB 비밀번호가 나와서 스샷도 지워주셔야 겠네요 😂

2024-12-27 05:38 UTC, boolYikes commented on dags/brz_industry_code_month.py
> +    ds_year, ds_month, ds_day = "{{ ds }}"[:4], "{{ ds }}"[5:7], "{{ ds }}"[8:10]
😂 위에 있는걸 까먹었습니다 ㅋㅋ 진자 템플릿 사용시 date = "{{ ds[:4] }}" 이렇게 쓰는 것도 틀린 방법일까요 ?

2024-12-27 12:25 UTC, cardia commented on dags/brz_industry_code_month.py
> +    ds_year, ds_month, ds_day = "{{ ds }}"[:4], "{{ ds }}"[5:7], "{{ ds }}"[8:10]
{{ ds }} 를 통채로 받아서 datetime으로 변환해서 사용해야겠죠.
string 상태에서 파싱하다가 어떤 값이 들어갈지 모르니까요.
코딩할 때는 원하는 값이 들어오지 않으면 에러를 발생시켜야 합니다.
하지면 "{{ ds }}"[:4] 이렇게 하면 슬라이싱을 잘 못 해서 숫자가 아닌 값들도 들어갈 수 있지만 에러가 나지 않을꺼예요. 직접 사용하는 곳에서 에러가 나거나, 파티션 키로 사용했다면 이상한 값이 파티션 키로 들어가게 되겠죠.

2024-12-27 12:28 UTC, cardia requested changes

2024-12-27 12:28 UTC, cardia commented on dags/brz_industry_code_month.py
> +    time.sleep(15)
P5; sleep은 왜 주나요??

2024-12-27 12:28 UTC, cardia commented on dags/brz_industry_code_month.py
> +    upload_kospi = S3CreateObjectOperator(
https://greppkdt-hq.slack.com/archives/C082WSHFF52/p1735275070101429

2024-12-27 12:28 UTC, cardia commented on dags/brz_industry_code_month.py
> +def fetch_industry_codes(market, referer, mktId, **ctxt):
P0; 아 여기도 이렇게 하셨네요 ㅠㅠ 늦게 찾아서 죄송합니다.
DAG을 정의하는 파이썬 파일에서는 DAG만 있어야 합니다. PythonOperator로 동작할 함수들은 다른 파일로 빼주세요.

2024-12-27 12:57 UTC, boolYikes commented on dags/brz_industry_code_month.py
> +    time.sleep(15)
url 요청시 반응이 꽤 느려서 넉넉하게 줬습니다! 😮

2024-12-28 13:47 UTC, cardia reviewed
이제 심각한 문제들은 많이 사라졌네요. 화이팅입니다!

2024-12-28 13:47 UTC, cardia commented on dags/brz_industry_code_monthly.py
> +import plugins.bronze.constants as C
P3; MARKETS을 바로 불러주시는게 좀 더 가독성이 좋습니다.
```suggestion
from plugins.bronze.constants import MARKETS
```

2024-12-28 13:47 UTC, cardia commented on dags/brz_industry_code_monthly.py
> +            # inner dependency
P2; 혹시나 하여 말씀드리면, 코드 짜실 때는 chatGPT는 웬만하면 사용하지 않으셨으면 합니다 😭

2024-12-28 13:47 UTC, cardia commented on dags/brz_industry_code_monthly.py
> +                previous >> codes_fetcher
P3; start와 end라는 dummy(empty)operator를 사용해서 시작점을 표시해주는 방법도 많이 사용합니다.

2024-12-28 13:47 UTC, cardia commented on dags/brz_industry_code_monthly.py
> +    kospi_kosdaq_group >> gics_codes_fetcher >> gics_uploader
P5; 병렬로 처리하지 않고 직렬로 쭉 늘어놓으신 것은 인프라의 한계 때문일까요?

2024-12-28 13:47 UTC, cardia commented on dags/plugins/bronze/pyops_extractors.py
> +import json
P3; 파일 이름이 요게 맞을까요? pyops는 무슨 뜻인가요??

2024-12-28 13:47 UTC, cardia commented on dags/plugins/bronze/pyops_uploaders.py
> +import json
업로드 파일을 따로 분리하셨군요. 좋습니다. 👍

2024-12-30 07:04 UTC, cardia reviewed
이제 거의 다 온 것 같습니다. 다른분들의 리뷰도 한번 받아보시죠.
파일 이름도 팀 내에서 통일을 하는게 좋을 것 같습니다.
보통은 dag이름과 폴더 이름, 파일 이름을 똑같이 가져가긴 합니다.

2024-12-30 07:04 UTC, cardia commented on dags/brz_industry_code_monthly/industry_code_main.py
> +            end_of_task_pair = DummyOperator(task_id=f"end_of_task_pair_{market}")
P1; 이렇게 하시면 매번 start_of_task_pair와 end_of_task_pair가 생성되지 않나요?? 의도하신 방향이 아닌 것 같아 P1의견 드립니다.

2024-12-30 07:04 UTC, cardia commented on dags/test_brz_crawl_image.py
> +import logging
P1; 이 파일은 crawler_image_test 라는 DAG이므로 그렇게 구성되어야 하겠습니다.

2024-12-30 07:04 UTC, cardia commented on dags/brz_industry_code_monthly/industry_code_main.py
> +    gics_uploader = PythonOperator(
P4; 으으음....제가 말씀드린 관심사의 분리는 도메인에 따른 분리 였습니다. 여기서는 도메인이 하나밖에 없어서 upload를 따로 떼실 필요는 없어 보이긴 하는데요. 그래도 로컬에 저장했다가 올리는 것이니까 괜찮아 보이긴 합니다. 이게 k8s에서 동작하는 것이었으면 에러가 날거예요.

2024-12-30 11:02 UTC, boolYikes reviewed
1. 업로더를 최대한 통일하기로 협의해서, s3 key와 payload만 받는 것으로 구조를 바꾸고, 

2. 업로더를 메인에서 따로 호출하지 않게 했습니다 (extractor에서 호출)

3. start 와 end 로 사용했던 dummy operator는, 업로더가 메인에서 사라졌기때문에 (더이상 루프 안에서 두 operator가 페어로 동작하지 않기때문에) 구분하는 의미가 없다고 판단해 삭제했습니다

4. test_crawl_image는 사용하지 않고 있고 나중에 따로 이미지를 사용한다 해도 재구성해야하기 때문에 삭제했습니다 (CI test용이 아닌데 명명때문에 의도치 않게 오해가 있을수도 ...)

@cardia 검토 부탁드립니다 ! 과연 이번엔 머지가 가능할것인가! 🤞🏼  ㅎㅎ 이미 저녁이지만 조은하루되십쇼~

2024-12-30 11:02 UTC, boolYikes commented on dags/plugins/bronze/pyops_extractors.py
> +import json
파이썬오퍼레이터를 분리한답시고 시작했는데,
나중에 보니 다른 헬퍼 함수들도 섞이게 됐습니다😖 정정하겠습니다 ㅋㅋ

2024-12-30 11:11 UTC, cardia approved these changes
LGTM! :+1:

2024-12-31 04:22 UTC, merged