[feature][TDET-49] A DAG for fetching coin, exchange rates and MSCI index
DE-ta-e-il/catch-me-my-capital pull request #5
Opened 2024-12-27 03:20 UTC by JeongMinHyeok

## 개요
코인 가격, 환율 종가, MSCI World Index와 MSCI Emerging Market Index 지수 정보를 수집하는 DAG 작성
각각 1일 주기로 수집하며, UTC 기준 자정에 데이터를 수집합니다.

## 변경 사항
`brz_coin_daily.py`
- [Binance API](https://www.binance.com/en/binance-api)를 이용해 25개 코인 데이터 수집
- 시초가, 고가, 저가, 종가 등의 데이터를 수집
- parquet 포맷으로 저장한 뒤 S3에 업로드

`brz_exchange_rate_daily.py`
- yfinance 라이브러리를 이용해 12개의 통화 쌍의 환율을 수집
- 원 기준 환율 6개, 달러 기준 환율 6개 수집
- parquet 포맷으로 저장한 뒤 S3에 업로드

`brz_msci_index_daily.py`
- [BusinessInsider Market](https://markets.businessinsider.com/index/msci-world)에 HTTP 요청을 이용해 데이터를 수집
- GET 요청을 보내는 URL은 환경변수로 저장
-  시초가, 고가, 저가, 종가의 데이터를 수집
- parquet 포맷으로 저장한 뒤 S3에 업로드

**.pre-commit-config.yaml** 파일은 수정사항 없습니다. (실수로 인해 커밋된 것 같습니다.)

## 테스트 결과

![image](https://github.com/user-attachments/assets/92fd58f1-8316-49b7-886b-803a9ba01024)
- Web UI 상 정상 실행 확인

![image](https://github.com/user-attachments/assets/a19e31bd-2f93-493a-a763-11b971788e48)
- S3 업로드 확인

![image](https://github.com/user-attachments/assets/b0e04270-3eeb-4845-a5da-5c94ea27cb92)
- 업로드된 파일 확인

## 리뷰 요청 사항

1. 코인(문자열 리스트 형태로 반환), 환율(dataframe 형태로 반환), MSCI(json 형태로 반환) 원본 데이터를 모두 parquet 형태로 변환해 저장하도록 구현했습니다. 혹시 이 부분이 성능 상 문제가 될 여지가 있을까요?

2. 환율과 시장지수(MSCI)의 경우 주말에는 데이터가 제공되지 않기 때문에, `AirflowSkipExcepiton`을 통해 task를 건너뛰고 있습니다. 이 로직이 적절할까요?

3. [파티셔닝 관련 질문에 대한 멘토님의 답변](https://www.notion.so/1596e9180a968161bc14d302a339bdb6?p=fa5dafd79f3349a9a3ed668f4b1ecf2d&pm=s)을 참고해서 `bronze/기능 이름/date=YYYY-MM-DD/file.parquet` 형태로 파티셔닝을 진행했습니다. 이 부분이 답변해주신 부분과 일치하는걸까요?

4. S3에 파일을 업로드할 때, `LocalFilesystemToS3Operator`를 사용하고 있습니다. 메모리를 활용해 업로드하는 방법도 있지만, 혹시 task가 여러 개 돌아갈 때 메모리 부하가 있을까 싶어 `로컬에  파일저장 -> S3에 업로드 -> 파일 삭제`의 흐름으로 코드를 구현했습니다. 혹시 이 방법이 효율을 떨어트리는 걸까요?

5. 함수와 변수의 이름이 명확할까요?

2024-12-27 05:07 UTC, cardia requested changes
모든 DAG에 적용하시고 다시 노티주세요~

2024-12-27 05:07 UTC, cardia commented on .pre-commit-config.yaml
> +        stages: [commit-msg]
P2; 윈도우에서 작업하시나요?? 팀 내에서 CRLF의 사용에 관해서 통일했으면 합니다.

2024-12-27 05:07 UTC, cardia commented on dags/brz_coin_daily.py
> +    # 임시 파일로 CSV 저장
P5; parquet이 맞죠? 😄

2024-12-27 05:07 UTC, cardia commented on dags/brz_coin_daily.py
> +            df = pd.DataFrame(
P2; pandas를 써야할 이유가 없어보이는데요. pandas로 구현하신 이유가 있나요?

2024-12-27 05:07 UTC, cardia commented on dags/brz_coin_daily.py
> +    s3_upload_task = LocalFilesystemToS3Operator(
P0; 이렇게 구현하면 안됩니다. operator는 상호독립적이어야 합니다.
boto3를 통해 직접 구현하세요.

2024-12-27 05:07 UTC, cardia commented on dags/brz_coin_daily.py
> +    "owner": "JeongMinHyeok",
P2; email 주소로 적으면 DAG 실패시 알람을 자동으로 보낼 수 있습니다.

2024-12-27 05:07 UTC, cardia commented on dags/brz_coin_daily.py
> +    fetch_and_upload_task = PythonOperator(
어떤 데이터를 fetch_and_upload하는지가 나타나면 좋겠습니다. task id랑 동일하게 사용하셔도 됩니다.

2024-12-27 05:07 UTC, cardia commented on dags/brz_coin_daily.py
> +    symbols = {
P3; 상수면 함수 밖에서 대문자로 정의해주세요.
상수들만 저장하는 클래스나 파일을 따로 둬도 좋겠습니다.

2024-12-27 05:07 UTC, cardia commented on dags/brz_exchange_rate_daily.py
> +    if execution_date.weekday() >= 5:  # 5: Saturday, 6: Sunday
P0; 아예 이 동작이 이뤄지지 않도록 task를 빼주세요. 코드레벨까지 내려와서 보지 않아도 되도록 합니다.
이렇게 Exception을 던지면 에러로 처리할텐데 그럼 재시작 policy에 따라 계속 재시작 되고, 결국은 실패로 기록될겁니다.

2024-12-27 05:07 UTC, cardia commented on dags/brz_exchange_rate_daily.py
> +def fetch_and_upload_exchange_rates(execution_date: datetime, **kwargs):
P0; DAG 파일과 PythonOperator에서 실행할 함수를 담는 파일은 구분해야 합니다.

2024-12-27 05:07 UTC, cardia commented on dags/brz_exchange_rate_daily.py
> +    schedule_interval="0 0 * * *",
P5; 알고계시겠지만, 이렇게 하면 0시에 동작하지 않습니다. 9시에 동작합니다.

2024-12-27 05:13 UTC, cardia commented
혹시 코드를 짜는데 chatGPT를 쓰고 계시다면 그러지 않으시는게 좋습니다. 😭

2024-12-27 05:27 UTC, JeongMinHyeok commented on .pre-commit-config.yaml
> +        stages: [commit-msg]
넵 팀원 중 저만 윈도우 환경에서 작업하고 있습니다. 팀원들과 이야기해서 통일하도록 하겠습니다!

2024-12-27 05:36 UTC, JeongMinHyeok commented on dags/brz_coin_daily.py
> +            df = pd.DataFrame(
json에는 칼럼 이름이 따로 주어지지 않고, parquet 포맷으로 저장할 목적으로 pandas를 사용했습니다. json 형태 그대로 저장하는게 더 좋은 방법일까요?

2024-12-27 05:47 UTC, JeongMinHyeok commented on dags/brz_exchange_rate_daily.py
> +    schedule_interval="0 0 * * *",
넵 UTC 기준 0시 (9시)에 동작하는게 의도였습니다!

2024-12-27 05:57 UTC, JeongMinHyeok commented on dags/brz_exchange_rate_daily.py
> +def fetch_and_upload_exchange_rates(execution_date: datetime, **kwargs):
DAG를 정의하는 파일과 task 실행 함수를 따로 저장하라는 말씀이실까요?
ex) 실행할 함수를 다른 파일에 담아 해당 모듈을 DAG 정의 파일에서 임포트

2024-12-27 07:43 UTC, JeongMinHyeok commented on dags/brz_coin_daily.py
> +    s3_upload_task = LocalFilesystemToS3Operator(
팀 공통 환경변수로 S3 Connection을 등록하고 사용할 예정입니다. 이 경우에 boto3 대신 S3Hook으로 구현해도 괜찮을까요?

2024-12-27 12:32 UTC, cardia requested changes

2024-12-27 12:32 UTC, cardia commented on dags/brz_coin_daily.py
> +            df = pd.DataFrame(
parquet으로 인해 pandas를 써야한다면 그럴 것 같습니다. 어차피 bronze레이어는 모든 데이터를 필터링 해야하니 columnar format을 쓸 이유도 없긴 하구요.

2024-12-27 12:32 UTC, cardia commented on dags/brz_coin_daily.py
> +            df = pd.DataFrame(
압축을 위해서는 csv도 괜찮겠네요.

2024-12-27 12:32 UTC, cardia commented on dags/brz_coin_daily.py
> +    s3_upload_task = LocalFilesystemToS3Operator(
S3Hook은 좋아보이네요.

2024-12-27 12:32 UTC, cardia commented on dags/brz_exchange_rate_daily.py
> +def fetch_and_upload_exchange_rates(execution_date: datetime, **kwargs):
넵

2024-12-29 12:12 UTC, JeongMinHyeok commented
안녕하세요 멘토님! 귀한 시간 내주셔서 정말 감사합니다.
지난 번 리뷰를 반영해 코드를 수정해보았습니다. 수정 내역은 아래에 간단히 정리했습니다.

### [수정 내역]
> P2; 윈도우에서 작업하시나요?? 팀 내에서 CRLF의 사용에 관해서 통일했으면 합니다.

- .pre-commit-config.yaml 파일을 LF 형태로 저장해 다시 push했습니다. (git config 설정을 통해 앞으로 CRLF 파일을 자동으로 LF로 변경해 커밋하도록 설정했습니다!)

> P2; pandas를 써야할 이유가 없어보이는데요. pandas로 구현하신 이유가 있나요? parquet으로 인해 pandas를 써야한다면 그럴 것 같습니다. 어차피 bronze레이어는 모든 데이터를 필터링 해야하니 columnar format을 쓸 이유도 없긴 하구요. 압축을 위해서는 csv도 괜찮겠네요.

- csv 라이브러리를 이용해 csv 포맷으로 저장한 후, 파일을 업로드하는 것으로 통일했습니다.

> S3Hook은 좋아보이네요.

- S3Hook을 이용해 `uploaders.py`를 구현했고, common 아래의 공통 함수로 만든 뒤 각 DAG에서 import하는 방식으로 구현했습니다.

> P0; DAG 파일과 PythonOperator에서 실행할 함수를 담는 파일은 구분해야 합니다.

- PythonOperator에서 실행할 함수를 `extractor`(각 기능별로), `uploader`(공통함수)로 구분했습니다. 또한 각 기능 별 사용할 상수들도 `constants.py`로 분리해 저장했습니다. DAG을 정의하는 파일은 각 디렉토리의 `{기능이름}_main.py`로 설정했습니다.

이외 수정사항은 아래와 같습니다.
- 각 기능 별 데이터 파일이 저장될 경로를 상수로 지정해 `uploader.py`에 전달 (Xcom을 사용하지 않음)
- default_args의 owner에 이메일 기입 (`common/constants.py`의 Owner 클래스 사용)
- 주말 및 공휴일 데이터 수집: 주말의 경우 schedule에서 제외 / 공휴일 데이터는 silver 테이블 조회하는 방향으로 구현예정 (구체적인 부분은 팀원들과 논의가 좀 더 필요할 것 같습니다.)
- PythonOperator 변수 이름에 어떤 데이터가 대상인지 표기

### [질문]
- `임시폴더에  파일저장 -> S3에 업로드 -> 파일 삭제` 흐름으로 데이터를 업로드를 하고 있습니다. 
파일을 저장하는 경로가 날짜만 바뀌는 패턴(ex. `COIN_TMP_FILE_PATH = "/tmp/coin_data_{{ ds }}.csv"`)이기 때문에
{{ds}}를 이용한 문자열 상수로 만든 뒤  `uploader.py`에 file_key를 전달하고 있는데요. Xcom으로 전달하는 것과 비교해 이 방식이 효율적일지, 또한 안전할지 궁금합니다.

감사합니다.

2024-12-30 06:57 UTC, cardia reviewed
이제 매우 많이 좋아졌고, 실제 실무에서 사용하는 코드의 형태가 되었네요.
질문들 답변에 따라 조금만 수정이 되거나, 그대로 올려도 좋을 상태입니다.

2024-12-30 06:57 UTC, cardia commented on dags/brz_msci_index_daily/msci_index_extractors.py
> +    with open(msci_index_tmp_file_path, "w") as csvfile:
P3; 아이코 이거 뭔가 제가 헷갈리게 말씀드린 것 같네용. 컬럼이름이나 내용등을 수정하고, parquet으로 저장하기 위해 pandas를 사용한다면 그걸 csv로 저장하는것도 괜찮다고 말씀드렸던 것입니다.
이렇게 이미 json으로 들어오는 데이터를 일부러 포맷을 통일해서 csv로 바꾸실 필요는 없습니다.
추후에 데이터를 csv로만 읽고 싶다고 한다면 csv로 바꾸셔도 되긴 합니다만 그럴 만한 이유가 있어야겠죠?

2024-12-30 06:57 UTC, cardia commented on dags/brz_coin_daily/coin_main.py
> +    fetch_coin_data_task >> upload_coin_data_to_s3_task
P4; 으으음....제가 말씀드린 관심사의 분리는 도메인에 따른 분리 였습니다. 여기서는 이미 코인, 환율, 인덱스지수 등으로 잘 분리를 해 주셔서 upload를 따로 떼실 필요는 없어 보이긴 하는데요. 그래도 로컬에 저장했다가 올리는 것이니까 괜찮아 보이긴 합니다. 이게 k8s에서 동작하는 것이었으면 에러가 날거예요.

2024-12-30 07:21 UTC, JeongMinHyeok commented on dags/brz_msci_index_daily/msci_index_extractors.py
> +    with open(msci_index_tmp_file_path, "w") as csvfile:
앗 아닙니다. 처음에는 말씀하신대로 이해했는데, 수정 중에 제가 한 번 더 꼬아서 생각한 것 같습니다 ㅎㅎ
지금 상황에서 csv로만 읽을 필요는 없으니, 각 데이터 소스 별 원본 그대로 업로드하는 방향으로 수정해보겠습니다.
다만, 데이터 소스 별로 약간씩의 차이가 있어 아래와 같이 코드를 수정하거나 현재 상태를 유지하려고 하는데, 이에 대한 멘토님 의견을 듣고싶습니다!

- MSCI 인덱스: 따로 칼럼이나 내용을 수정할 필요가 없으니 **json(원본형태) 그대로 저장하는 코드로 수정**하려고합니다.
- 코인: json으로 반환되지만 **칼럼 수정이 필요**(수치 데이터만 list 형태로 주는 형태)합니다. 칼럼 명을 추가한 뒤, csv파일로 저장하는 **현재 코드를 유지**하려고 합니다.
- 환율: yfinance 라이브러리 종속성으로 인해 **반환값이 Dataframe으로 주어집니다.** to_csv() 메서드를 통해 바로 csv파일로 저장할 수 있어, **현재 코드를 유지**하려고 합니다.

2024-12-30 15:49 UTC, JeongMinHyeok commented
### [수정내역]

1. upload task를 분리하지 않고, extractors에서 호출해 하나의 task에서 수행하도록 수정했습니다.

2. msci index의 경우 원본 그대로 json파일로 저장해 업로드하도록 수정했습니다. (코인과 환율은 csv로 저장하는 코드로 유지했습니다. 아래의 이유로 인해 msci index만 json으로 저장하는 것으로 수정하는 것으로 판단했습니다.)

> 지금 상황에서 csv로만 읽을 필요는 없으니, 각 데이터 소스 별 원본 그대로 업로드하는 방향으로 수정해보겠습니다.
> 다만, 데이터 소스 별로 약간씩의 차이가 있어 아래와 같이 코드를 수정하거나 현재 상태를 유지하려고 하는데, 이에 대한 멘토님 의견을 듣고싶습니다!
> 
> MSCI 인덱스: 따로 칼럼이나 내용을 수정할 필요가 없으니 json(원본형태) 그대로 저장하는 코드로 수정하려고합니다.
> 코인: json으로 반환되지만 칼럼 수정이 필요(수치 데이터만 list 형태로 주는 형태)합니다. 칼럼 명을 추가한 뒤, csv파일로 저장하는 현재 코드를 유지하려고 합니다.
> 환율: yfinance 라이브러리 종속성에 Pandas가 포함되어 있고, 데이터의 형태가 Dataframe으로 주어집니다. to_csv() 메서드를 통해 바로 csv파일로 저장할 수 있어, 현재 코드를 유지하려고 합니다.

3. 각 디렉토리의 `__init__.py`에 각 모듈을 미리 선언해 패키지로 만들고, main에 import할 때 좀 더 간결하게 작성할 수 있도록 수정했습니다.

(전)
```
from brz_coin_daily.coin_constants import COIN_DATA_S3_KEY, COIN_TMP_FILE_PATH, SYMBOLS
from brz_coin_daily.coin_extractors import fetch_coin_data
```
(후)
`from brz_coin_daily import (
    COIN_DATA_S3_KEY,
    COIN_TMP_FILE_PATH,
    SYMBOLS,
    fetch_coin_data,
)`

항상 감사합니다! 2024년 행복하게 마무리하셨으면 좋겠습니다. 새해 복 많이 받으세요!🙌

2025-01-01 13:52 UTC, cardia approved these changes
새해 복 많이 받으세요! LGTM! 고생하셨습니다! 🎉

2025-01-03 02:43 UTC, merged