[feature] [TDET-51] A DAG for fetching commodities(oil, gold) data
DE-ta-e-il/catch-me-my-capital pull request #6
Opened 2024-12-27 08:52 UTC by mangodm-web

## 개요

yfinance를 활용하여 일 단위(daily)로 원유, 금 가격 데이터를 수집하는 DAG을 작성했습니다.
수집 대상은 원유(WTI, 브렌트)와 금 선물 데이터이, 하루에 총 3건의 데이터를 수집합니다.

## 변경 사항

DAG은 아래 세 개의 태스크로 구성했습니다.

<img width="577" alt="Screenshot 2024-12-27 at 4 33 57 PM" src="https://github.com/user-attachments/assets/02bcfae5-db97-4bd4-83e5-4677796a0f1e" />

1. `ingest_data_to_s3_landing`: yfinance를 사용하여 가격 데이터를 수집하고, 임시 저장소(S3의 landing 레이어)에 저장
2. `validate_data`: landing 레이어에 저장된 데이터에 대한 검증(빈 파일 여부, 필수 컬럼 포함 여부) 수행
3. `upload_data_to_s3_bronze`: landing 레이어에 저장된 데이터를 실제 저장소(S3의 bronze 레이어)로 이동

## 테스트 결과
로컬 환경에서 DAG을 실행하여, 파이프라인이 의도한 대로 동작하는 것을 확인했습니다.

> DAG 실행 결과: 빨간색 박스로 표시한 영역이 최근 실행된 정상 기록입니다.
<img width="462" alt="Screenshot 2024-12-27 at 5 45 12 PM" src="https://github.com/user-attachments/assets/4ca7521b-5791-44e9-b918-6ce4199f0ab5" />

> 파이프라인 실행 후, S3 bronze 레이어에 데이터가 적재된 화면입니다.
<img width="1000" alt="Screenshot 2024-12-27 at 4 35 23 PM" src="https://github.com/user-attachments/assets/4044d905-d584-4dee-8498-318afb77986e" />

## 리뷰 요청 사항
**1. 상수화의 필요성 및 선언 위치의 적절성**
- 유지보수성을 높이기 위해, 반복적으로 사용되는 오너 정보와 레이어 정보를 클래스 기반 상수로 선언하고, 활용하였습니다.
- 현재 이 상수들을 [`dags/constants.py`](https://github.com/DE-ta-e-il/catch-me-my-capital/blob/feature/TDET-51-bronze-commodities-daily/dags/constants.py) 파일에 정의했는데, 이러한 방식과 파일 위치가 적절한지 리뷰해주실 수 있을까요?

**2. 현재 파이프라인 구성의 적절성**
- 한 태스크에서 데이터를 수집하고, S3의 bronze 레이어로의 저장을 한 번에 처리하는 방법을 고려했으나, 데이터 수집과 저장이 각기 다른 목적을 가지기 때문에 이를 구분하는 것이 관리 측면에서 보다 적절하다고 판단하여 현재와 같이 태스크를 구분했습니다. 
- 데이터를 로컬에 임시 파일로 저장하고, XCom으로 이후 태스크에 파일 경로를 전달하는 것을 고려했지만, 워커 노드가 여러 대로 구성될 경우 파일 저장소에 접근하기 어렵다는 점을 고려해 파일을 S3에 landing 레이어에 추가하도록 구현했습니다.
- 하지만, 이렇게 해서 DAG의 복잡성이 불필요하게 늘어난 것은 아닌지 우려가 됩니다. 구성이 적절한지에 대한 검토 부탁 드립니다.

수정/보완이 필요한 부분이 있으면, 언제든지 편하게 말씀해주세요. 감사합니다. 😃

2024-12-28 13:57 UTC, cardia requested changes
1. 데이터 수집
2. 상태 확인
3. S3 재 저장
DAG을 이런 단계를 거치도록 구현하신 것으로 보입니다. 그런데 transaction느낌으로 작업을 묶어서 생각해보면 1번에서 들어온 데이터가 문제가 있다면 다시 데이터를 가져와야 하지 않나요? 지금 형태라면 2번 작업이 실패하면 2번 task만 재 구동 될텐데, 그러면 같은 결과만 나오게 되고, 결국 DAGRUN이 실패하게 될겁니다. 1, 2, 3 일련의 과정이 모두 통합되어야 한다고 봅니다. 그래야 문제가 발생하면 실패하고, 다시 데이터를 수집해 올 수 있게 되니까요.
여러분은 각각 하나의 DAG을 구현하시지만 그것들이 모였을 때에는 서로를 구분하기 힘들게 될 수 있습니다. 슬랙에 올려드린 폴더링을 확인해 보세요.

2024-12-28 13:57 UTC, cardia commented on dags/constants.py
> +class Owner:
P5; Enum 클래스를 상속하여 정의하기도 하지만 이런 방법도 너무 좋습니다. 👍

2024-12-28 13:57 UTC, cardia commented on dags/brz_commodities_daily.py
> +        from airflow.exceptions import AirflowSkipException
P0; local import는 패키지 이름별로 충돌이 나거나 하는 등, 꼭 필요한 경우를 제외하면 하지 않습니다. 모두 최 상단에 위치시켜주세요.
그리고 함수들을 DAG과 분리해주세요.

2024-12-28 19:28 UTC, mangodm-web commented on dags/brz_commodities_daily.py
> +        from airflow.exceptions import AirflowSkipException
> local import 사용 관련
[Airflow 공식 문서의 "Top-Level 코드는 피하라."](https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code)라는 글의 내용을 잘못 이해하고, 적용했습니다. 기본적으로는 최상단 import를 사용하는 것이고, pandas나 torch 같은 무거운 모듈에만 제한적으로 local import를 적용하라는 말이었군요... 😢 이 부분 반영하도록 하겠습니다!

> 함수들을 DAG과 분리
네! 관심사에 따라 DAG을 정의한 파일과 이외의 파일들로 분리해보겠습니다.

2024-12-28 19:34 UTC, mangodm-web commented on dags/constants.py
> +class Owner:
말씀해주신 Enum 클래스를 사용하는 방법을 조사해보니, Enum을 사용하는 것이 의미적으로나 관리 측면에서도 더 적절한 방법이라는 생각이 드네요! 다만, 기본 Enum을 사용하면 명시적으로 .value를 호출해야 하는 등 별도의 처리가 필요해서 이러한 번거로움을 해결하기 위해 파이썬 3.11부터 추가된 [StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum)을 적용해보려고 합니다. 😃

2024-12-30 06:39 UTC, cardia commented on dags/brz_commodities_daily/commodities_tasks.py
> +            yf.download(self.ticker_list, start=start_date, end=end_date, interval="1d")
P2; yf를 사용할 때 꼭 pandas를 사용해야 하나요? 저는 pandas조차 꽤 무겁다고 생각하는 1인입니다 ㅋㅋ

2024-12-30 06:39 UTC, cardia commented on dags/brz_commodities_daily/commodities_main.py
> +TICKER_LIST = ["CL=F", "BZ=F", "GC=F"]
P2; 이게 따로따로 task가 생길게 아니고 하나의 task에서 모두 실행하게 된다면 이 값들도 CommoditiesPipeline 클래스 안으로 들어가야 하지 않을까요?

2024-12-30 06:39 UTC, cardia commented on dags/brz_commodities_daily/commodities_main.py
> +    fetch_commodities_data = PythonOperator(
P4; 으으음....이렇게까지 파이썬으로 짜신다고 하면 보통은 PythonOperator를 상속한 Operator를 커스텀하게 구현하긴 하는데요. 아직은 한번만 쓰이긴 하니까 그냥 이대로 구현하셔도 문제는 없겠습니다.

2025-01-01 14:02 UTC, cardia commented on dags/brz_commodities_daily/commodities_tasks.py
> +            yf.download(self.ticker_list, start=start_date, end=end_date, interval="1d")
이거 좀 찾아보니까 어쩔 수 없는 것 같네요. 그럼 그냥 두셔도 됩니다. 😭

2025-01-02 18:36 UTC, mangodm-web commented on dags/brz_commodities_daily/commodities_main.py
> +    fetch_commodities_data = PythonOperator(
확인해보니, 다른 DAG에서도 yfinance를 이용하실 분들이 있다고 하셔서,
지금 구현한 부분을 커스텀 오퍼레이터 형태로 변경해보려고 합니다.
곧 작업하고, 완료되면 멘션 드리도록 하겠습니다. 감사합니다! 😸

2025-01-05 15:28 UTC, cardia approved these changes
고고!

2025-01-05 15:29 UTC, merged