[feat] [TDET-59] A DAG for fetching Korean ETF data
DE-ta-e-il/catch-me-my-capital pull request #7
Opened 2024-12-27 10:45 UTC by J-EUM

## 개요

- 매일 평일에 국내 ETF 데이터를 수집하는 DAG
- 평일 기준 daily로 실행됩니다.
- [공공데이터 API](https://www.data.go.kr/data/15094806/openapi.do#)를 통해 해당 일자의 모든 ETF 정보를 수집합니다.
- 평일이 휴장일인 경우 나머지 task는 skip됩니다.
- 해당 API에서 2020년 보다 과거 데이터는 제공하지 않아서 2019.12.31 이전 데이터는 [krx 웹](http://data.krx.co.kr/contents/MDC/MDI/mdiLoader/index.cmd?menuId=MDC0201020101)을 이용합니다.

## 변경 사항

- execution date가 휴장일이면 skip합니다.
- 휴장일이 아니라면 데이터를 수집합니다
  - 2019-12-31이전: fetch_etf_krx_web
  - 2020-01-01이후: fetch_etf_krx_api
- 데이터가 없으면 소스 쪽에서 데이터가 업데이트 되지 않은 것으로 보고 1시간마다 재시도 합니다
  - 데이터 소스 쪽 정확한 업데이트 시간을 알지 못해서 이렇게 설정했습니다.
  - 과거에 api 테스트에서 이른 아침 시간대에 전날의 데이터가 아직 업데이트되지 않아 0건이 반환되는 것 확인했습니다.
- 데이터를 S3에 json 포맷으로 저장 합니다.
  - bronze/kr_etf/date=YYYY-MM-DD/data.json

## 테스트 결과

### 로컬 실행 결과
<img width="268" alt="image" src="https://github.com/user-attachments/assets/4799584f-2870-42ae-9533-34de1a633e6e" />

- 2020년 이후: fetch_etf_krx_api
<img width="657" alt="image" src="https://github.com/user-attachments/assets/a10a9569-6f6a-4ec7-9532-fbfcd0ce9b07" />

- 휴일: skip
<img width="649" alt="image" src="https://github.com/user-attachments/assets/f023643a-540d-420f-bfdc-39d28301785e" />

- S3 업로드 된 데이터
![image](https://github.com/user-attachments/assets/7de23c9b-17d8-4388-a437-e88e03319954)

## 리뷰 요청 사항

1. 2015-01-01를 기준으로 이후 데이터를 수집하기로 결정하고 처음에는 DAG start_date를 2015-01-01로 둔 후, catchup=True설정을 해서 데이터를 수집하려고 했습니다. 그래서 날짜에 따라 [fetch_etf_krx_web, fetch_etf_krx_api]중 하나의 task가 실행되도록 구현하게 됐는데, 이 부분은 그냥 빼고 fetch_etf_krx_api만 남기는게 좋을까요?
2. 이렇게 어느 시점 이후로 데이터 소스가 완전히 변경되는 경우에 branch operator로 처리하기도 하나요?
5. 평일 중에 휴장일 스킵 처리를 위한 함수를 일단 한 파일 내에 작성을 했는데, 저희가 휴장일 데이터 자체도 수집할 예정입니다. 그렇다면 매일 api 호출하는 것 보다는 수집해 놓은 데이터를 이용하는 방법으로 바꾸는 게 좋겠죠?
6. 지금처럼 휴일은 미리 알고 데이터 수집하지 않는 방법/그냥 주는대로 받아서 0개 저장하는 방법 뭐가 좋은가요?
7. 데이터가 0개일때 아직 업데이트 되지 않은 것으로 보고 실패시킨 후 retry되도록 했는데, 다른 문제로 실패한 경우에도 retry되는 단점이 있습니다. 그냥 모든 retry가 끝난 후에도 실패한 경우를 체크하는 것으로 충분할까요?

2024-12-27 12:46 UTC, cardia commented
휴장일을 판단할 때 ShortCircuitOperator를 쓰기도 합니다. BranchPythonOperator도 괜찮아요.
일단 본문에 있는 질문부터 답변 드립니다.
1. 이건 수집하는 데이터소스 쪽에서 변경된 부분인가 보네요. 말씀하신대로 구현해도 괜찮지만 저라면 DAG을 분리할 것 같아요. fetch_etf_krx_web는 이후에는 필요 없는 코드기 때문에 fetch_etf_krx_web이 동작하는 기간을 정해서 동작하고, 그 이후는 fetch_etf_krx_api DAG으로 동작시킬 것 같습니다.
2. 할 수도 있을 것 같은데, 일부러 복잡도를 높일 필요는 없어서 1번의 방법을 권장해봅니다. P4정도의 의견입니다.
3. 이 질문은 잘 이해를 못 했습니다. 아직 코드를 보지 못 해서 그럴지도 모르겠네요. 휴장일 데이터를 어떻게 수집하나요??
수집한 놓은 데이터로 휴장일 데이터를 이용한다(???)는 부분도 이해가 불가능했습니다 😭 
4. 공휴일 데이터를 수집하지 않나요? 보통은 공공데이터를 이용해서 calendar정보를 받아와서 활용합니다.
5. 아니요. 실패랑 의도된 값은 명백히 구분해야 합니다. 조건을 구별해서 적용해보시죠.

2024-12-27 13:14 UTC, cardia requested changes

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +import xml.etree.ElementTree as ET
으악 xml.............

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +def _is_holiday_today(year, month, today):
P0; https://greppkdt-hq.slack.com/archives/C082WSHFF52/p1735303428653039

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +    date = datetime.strptime(ds_nodash, "%Y%m%d")
👍 이게 순리입니다. 문자열을 슬라이싱해서 int로 바꿔서 사용하면 안됩니다.

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +    month = date.strftime("%m")
P3; 오잉? 이렇게도 됩니다. year, month, day, hour, minute, second, microsecond 다 있어요~
```suggestion
    month = date.month
```

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +    if _is_holiday_today(year, month, ds_nodash):
P3; date만 넘겨서 받아서 쓰는 것은 어떤가요?

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +        locdates.append(last_weekday_nodash)
이 부분 설명이 필요할 것 같아요. 이런 처리를 해야하는 이유가 있나요??

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +        "User-Agent": "PostmanRuntime/7.42.0",
P4; 이 값은 없어도 될껄요??

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +    return json.dumps(items)
P0; xcom은 어떤 데이터가 얼만큼 들어올지도 모르는 값을 저장해서는 안됩니다.
차라리 하나의 task에서 S3 upload까지 하도록 각 task가 stateless하게 작성되어야합니다.

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +    "retry_delay": timedelta(hours=1),
P5; 엇 이렇게 오래 텀을 둬도 괜찮나요?
daily DAG이라고 해도 보통은 10분 정도 텀을 둡니다.

2024-12-27 13:14 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +    return json.dumps(all_items)
P1; https://greppkdt-hq.slack.com/archives/C082WSHFF52/p1735305087135289

2024-12-28 08:52 UTC, J-EUM commented on dags/brz_kr_etf_daily.py
> +    month = date.strftime("%m")
아 이게 month를 두글자로 뽑으려고 저렇게 된건데 코드로 보니까 이상하네요!
date.month로 먼저 뽑아 놓고 요청 인자로 넣을때 두글자 스트링으로 변경하는 것으로 수정해보겠습니다.
(아래 리뷰도 참고해서 date 통으로 넘긴 후 함수 안에서 처리하겠습니다)

2024-12-28 08:57 UTC, J-EUM commented on dags/brz_kr_etf_daily.py
> +    if _is_holiday_today(year, month, ds_nodash):
그렇네요! 수정하겠습니다.

2024-12-28 09:05 UTC, J-EUM commented on dags/brz_kr_etf_daily.py
> +        locdates.append(last_weekday_nodash)
[한국거래소 휴장일](https://open.krx.co.kr/contents/MKD/01/0110/01100305/MKD01100305.jsp)을 확인해 보니 매년 마지막 평일이 연말 휴장일이라서 공휴일에 추가로 마지막 평일까지 확인하기 위해서 넣었습니다.

그런데 지금 검색을 해보니 매년 마지막 평일이긴 한데, 암묵적으로만 정해진 것인지 매년 "올해 연말 휴장일은 12월 00일"이라는 기사가 나네요. `공휴일 api + 마지막 평일`로 구분하는 방법 보다 위의 한국거래소 페이지를 이용해서 휴장일 판별을 하는 게 좋을까요?

2024-12-28 09:11 UTC, J-EUM commented on dags/brz_kr_etf_daily.py
> +        "User-Agent": "PostmanRuntime/7.42.0",
안 넣으면 403이 오더라구요..
이 부분(fetch_etf_krx_web)은 요청사항 1번 질문에 답변 주신것 처럼 통으로 없애는 방향으로 가겠습니다!

2024-12-28 09:26 UTC, J-EUM commented on dags/brz_kr_etf_daily.py
> +    "retry_delay": timedelta(hours=1),
소스 쪽 데이터 업데이트 시간이 확실하지 않아서 이렇게 구현을 해 두었습니다.
전에 월요일 아침에 주말 전 금요일 데이터를 조회했을 때 0건이 나오다가 오후에는 잘 나오는 것을 확인 했습니다.
다음 영업일날 배치로 데이터를 업데이트 하는 것 같은데, 업데이트 시간을 몰라서 1시간에 한번 확인하도록 한 것인데...공공데이터쪽에 업데이트 시간 문의를 한번 해 보겠습니다!

2024-12-28 11:17 UTC, J-EUM commented
> 휴장일을 판단할 때 ShortCircuitOperator를 쓰기도 합니다. BranchPythonOperator도 괜찮아요. ~그리고 EmptyOperator가 아니라 DummyOperator입니다.~ 코드에는 제대로 쓰셨는데 그림을 수정하셔야겠네요 😓 일단 본문에 있는 질문부터 답변 드립니다.

확인해보니 [Airflow 2.4](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#id21)부터 DummyOperator -> EmptyOperator로 변경되었다고 합니다. DummyOperator로 코드를 작성해도 내부에서 EmptyOperator로 구현해서 그림에 글씨도 EmptyOperator로 나오는 것 같습니다. (저희는 2.10.1을 쓰는 중입니다)
![image](https://github.com/user-attachments/assets/e57efbd3-d76c-4927-b6ad-b00770f53c80)

그리고 사실은..2.10.1에는 airflow.operators.dummy가 없어서 ide에서 import 부분이 아래처럼 나오는데 코드에서도 EmptyOperator로 변경해도 될까요?
(작동은 잘 돼서 모른척 하다가 이제서야 왜 빨간줄이 뜨는지 알게됐네요 😅)
![image](https://github.com/user-attachments/assets/7bd74580-25b7-4635-b27c-e3151b820850)


> 1. 이건 수집하는 데이터소스 쪽에서 변경된 부분인가 보네요. 말씀하신대로 구현해도 괜찮지만 저라면 DAG을 분리할 것 같아요. fetch_etf_krx_web는 이후에는 필요 없는 코드기 때문에 fetch_etf_krx_web이 동작하는 기간을 정해서 동작하고, 그 이후는 fetch_etf_krx_api DAG으로 동작시킬 것 같습니다.
> 2. 할 수도 있을 것 같은데, 일부러 복잡도를 높일 필요는 없어서 1번의 방법을 권장해봅니다. P4정도의 의견입니다.

1번 방법으로 가겠습니다

> 3. 이 질문은 잘 이해를 못 했습니다. 아직 코드를 보지 못 해서 그럴지도 모르겠네요. 휴장일 데이터를 어떻게 수집하나요??
>    수집한 놓은 데이터로 휴장일 데이터를 이용한다(???)는 부분도 이해가 불가능했습니다 😭

다른 데이터 수집하듯이 휴장일 데이터도 2015년부터 수집하기로 했는데, 
용도는: 나중에 저희 결과물에서 휴장일도 보여주면 데이터가 없는 날짜에 대한 설명이 될 수 있을 것 같으니 좋을 것 같다.(결과물의 형태는 아직 모르겠지만요) -> 이런 내용이었습니다. 

그래서 수집해놓은 휴장일 목록이 있으면 `branch_task`에서 휴장일 판단시 api 응답 대신 저장해 놓은 휴장일을 읽어서 이용하면 되지 않을까?하는 생각이었는데....
~사실 휴장일도 처음에는 s3 bronze에 저장할 듯 한데, 뭔가를 판별하기 위해서 bronze layer 데이터를 읽는다는 게 이상하긴 합니다 😅 그렇다고 이것만 앞서나가서 다른데 저장하는 것도 이상합니다!~
결론은! 지금처럼 api 호출한 결과를 사용하면 되겠죠?

2024-12-28 13:20 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +    month = date.strftime("%m")
아 맞다 ㅠㅠ 그렇군요. 그럼 지금 형태로도 괜찮습니다!

2024-12-28 13:21 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +        locdates.append(last_weekday_nodash)
팀 전체적으로 휴장일을 써야할 것 같은데, calendar를 거래소나 공공데이터를 사용해서 수집해서 사용하는게 좋을 것 같아요.

2024-12-28 13:25 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +        "User-Agent": "PostmanRuntime/7.42.0",
아하 그럼 `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.5938.132 Safari/537.36` 요렇게 하는게 제일 호환성이 높을 것 같아요. 우분투에서 chrome을 사용해서 호출하는 user-agent 값입니다.

2024-12-28 13:25 UTC, cardia commented on dags/brz_kr_etf_daily.py
> +    "retry_delay": timedelta(hours=1),
넵 그런 사유가 있다면 현 상태 유지하셔도 괜찮습니다. P5의견이었습니다 ㅎㅎ

2024-12-28 13:30 UTC, cardia commented
> > 휴장일을 판단할 때 ShortCircuitOperator를 쓰기도 합니다. BranchPythonOperator도 괜찮아요. ~그리고 EmptyOperator가 아니라 DummyOperator입니다.~ 코드에는 제대로 쓰셨는데 그림을 수정하셔야겠네요 😓 일단 본문에 있는 질문부터 답변 드립니다.
> 
> 확인해보니 [Airflow 2.4](https://airflow.apache.org/docs/apache-airflow/2.4.0/release_notes.html#id21)부터 DummyOperator -> EmptyOperator로 변경되었다고 합니다. DummyOperator로 코드를 작성해도 내부에서 EmptyOperator로 구현해서 그림에 글씨도 EmptyOperator로 나오는 것 같습니다. (저희는 2.10.1을 쓰는 중입니다) ![image](https://private-user-images.githubusercontent.com/97498663/399071565-e57efbd3-d76c-4927-b6ad-b00770f53c80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTIxMTcsIm5iZiI6MTczNTM5MTgxNywicGF0aCI6Ii85NzQ5ODY2My8zOTkwNzE1NjUtZTU3ZWZiZDMtZDc2Yy00OTI3LWI2YWQtYjAwNzcwZjUzYzgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDEzMTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1YWYzZTllMmNiZDBiODgxMDk4M2Q5ZDFlODZiOWMwMDM3NWU5ZmI4Y2Q4ZDMyYjY4ODYyOTI3ZWNkZTg0OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-BD43PoCRgyglTLLpbGOizeLcp2XPDFdMXoPvRp6NVk)
> 
> 그리고 사실은..2.10.1에는 airflow.operators.dummy가 없어서 ide에서 import 부분이 아래처럼 나오는데 코드에서도 EmptyOperator로 변경해도 될까요? (작동은 잘 돼서 모른척 하다가 이제서야 왜 빨간줄이 뜨는지 알게됐네요 😅) ![image](https://private-user-images.githubusercontent.com/97498663/399073972-7bd74580-25b7-4635-b27c-e3151b820850.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTIxMTcsIm5iZiI6MTczNTM5MTgxNywicGF0aCI6Ii85NzQ5ODY2My8zOTkwNzM5NzItN2JkNzQ1ODAtMjViNy00NjM1LWIyN2MtZTMxNTFiODIwODUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDEzMTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhY2UyMzMyMjJkZjAzZWZiOGY1ZTRlZTI5Zjc2ODAwMDlhNDRhOTkzMDgzZDI0ZTM3NGRkMjZjYjU3MWRmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q32Y_rSOY_tdJZ_YxKabdhfipgWpBvudGIgjNtYxh_w)
> 
> > 1. 이건 수집하는 데이터소스 쪽에서 변경된 부분인가 보네요. 말씀하신대로 구현해도 괜찮지만 저라면 DAG을 분리할 것 같아요. fetch_etf_krx_web는 이후에는 필요 없는 코드기 때문에 fetch_etf_krx_web이 동작하는 기간을 정해서 동작하고, 그 이후는 fetch_etf_krx_api DAG으로 동작시킬 것 같습니다.
> > 2. 할 수도 있을 것 같은데, 일부러 복잡도를 높일 필요는 없어서 1번의 방법을 권장해봅니다. P4정도의 의견입니다.
> 
> 1번 방법으로 가겠습니다
> 
> > 3. 이 질문은 잘 이해를 못 했습니다. 아직 코드를 보지 못 해서 그럴지도 모르겠네요. 휴장일 데이터를 어떻게 수집하나요??
> >    수집한 놓은 데이터로 휴장일 데이터를 이용한다(???)는 부분도 이해가 불가능했습니다 😭
> 
> 다른 데이터 수집하듯이 휴장일 데이터도 2015년부터 수집하기로 했는데, 용도는: 나중에 저희 결과물에서 휴장일도 보여주면 데이터가 없는 날짜에 대한 설명이 될 수 있을 것 같으니 좋을 것 같다.(결과물의 형태는 아직 모르겠지만요) -> 이런 내용이었습니다.
> 
> 그래서 수집해놓은 휴장일 목록이 있으면 `branch_task`에서 휴장일 판단시 api 응답 대신 저장해 놓은 휴장일을 읽어서 이용하면 되지 않을까?하는 생각이었는데.... ~사실 휴장일도 처음에는 s3 bronze에 저장할 듯 한데, 뭔가를 판별하기 위해서 bronze layer 데이터를 읽는다는 게 이상하긴 합니다 😅 그렇다고 이것만 앞서나가서 다른데 저장하는 것도 이상합니다!~ 결론은! 지금처럼 api 호출한 결과를 사용하면 되겠죠?

1. 아하! 저도 처음 알았습니다. 제가 지금까지 다닌 회사들에서 사용한 가장 최신은 2.7.3입니다 ㅎㅎ 좋은 정보 감사합니당
2. 넵! 그러면 start_date와 end_date를 잘 작성해 주시면 되겠습니다!
3. 저라면, 경험한 회사들에서는 모두, 휴일 데이터를 받아서 bronze에 넣고, 날짜 표기에 관련된 모든 정보들, 예를 들어 그 달에 마지막 일자, 그 달의 첫 요일, 마지막 요일, 그 주의 시작일(월요일이냐 일요일이냐 기준에 따라) 같은 정보를 담아서 silver 테이블로 생성하고, 이 데이터를 조회했었습니다. 이렇게 하면 팀 내의 다른 파이프라인에서도 사용할 수 있게 되니까요!

2024-12-30 12:11 UTC, J-EUM commented
리뷰 반영한 변경사항입니다!
## 변경 사항
**DAG 분리**
- 기존에 2020년을 기점으로 BranchPythonOperator를 통해 분기해서 동작하던 DAG를 두 개의 DAG로 분리했습니다.
  - `brz_kr_etf_daily`: 2020년 데이터부터 수집하는 DAG
  - `brz_kr_etf_daily_deprecated`: 2019년까지의 데이터를 수집하는 DAG
- DAG 정의 파일과 Task 파일 분리


**DAG 구조 변경**
<img width="478" alt="image" src="https://github.com/user-attachments/assets/18c67c22-7574-4e28-948b-747392b20cfd" />

- 데이터 수집과 저장을 하나의 Task에서 처리하도록 변경했습니다.


**휴장일 체크**
- `verify_market_open`
- 기존에 휴장일 판단 후 3가지 옵션이 있었는데, DAG를 분리하면서 [스킵하거나, 다음 Task(수집)] 택1을 하게 되어서 ShortCircuitOperator로 변경했습니다.
- ShortCircuitOperator에서 True 리턴 후 다음 Task가 실행되기 때문에 휴장일을 False로 반환하도록 함수명 변경 _is_holiday_today() -> is_kr_market_open_today()
  - 현재 API 응답으로 처리하도록 구현된 기존 방식 그대로 두었는데, 휴장일 수집 DAG 구현 후 이 부분의 코드를 silver layer의 데이터로 처리하도록 변경 예정입니다.

**데이터 수집, 저장**
- 데이터 수집과 저장을 하나의 Task에서 처리하도록 변경했습니다.
- S3에 데이터를 저장하는 코드는 dags/common/s3_utils.py에 구현
- 소스쪽 데이터 업데이트 문제로 count가 0일 때 retry하도록 했고, 이 경우가 아닐 시 AirflowFailException으로 retry 없이 실패처리 되도록 변경했습니다.

## 테스트 결과
<img width="768" alt="image" src="https://github.com/user-attachments/assets/80089427-820c-4c33-8210-2f446495db5a" />

2025-01-01 14:00 UTC, cardia approved these changes
새해 복 많이 받으세요! LGTM! 고생하셨습니다! 🎉 
is_kr_market_open_today() 를 대체할 함수를 꼭 분리하지는 않아도 될 것 같아요. 어차피 한 DAG에서 사용되는 함수니까요.

2025-01-06 05:19 UTC, J-EUM commented
[f79eb0d](https://github.com/DE-ta-e-il/catch-me-my-capital/pull/7/commits/f79eb0ddd6cb89f5a17329c2e9f23aba05e8dfeb)

기존에 api를 사용해서 휴장일 처리하던 부분을 silver layer 데이터를 이용한 처리 방식으로 바꾸었습니다.
<img width="635" alt="image" src="https://github.com/user-attachments/assets/527fe9a6-1801-4a33-9ffc-06eff5f724b8" />

- `get_workday_info`
  - Redshift에 저장된 데이터를 확인합니다.
  - 현재 날짜, 현재 날짜의 휴장일 여부, 가장 최근의 working day를 반환합니다.
- `verify_market_open`
  - 휴장일인 경우: skip
  - 아닌 경우: 이전 working day 날짜를 xcom에 저장
- `fetch_etf_krx_api`
  - 해당 날짜의 데이터를 수집해서 s3 버킷에 저장합니다.

2025-01-06 11:18 UTC, cardia approved these changes

2025-01-06 11:33 UTC, merged